# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-16 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=32, unique=True)),
                ('ctime', models.DateTimeField(auto_now_add=True, null=True)),
                ('uptime', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=32, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(help_text='pwd', max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('test', models.EmailField(error_messages={'invalid': '\u8bf7\u8f93\u5165\u5bc6\u7801'}, max_length=19, null=True)),
                ('user_type_id', models.IntegerField(choices=[(1, '\u8d85\u7ea7\u7528\u6237'), (2, '\u666e\u901a\u7528\u6237'), (3, '\u666e\u666e\u901a\u7528\u6237')], default=1)),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptest.UserGroup')),
            ],
        ),
    ]
