# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-28 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0002_auto_20180516_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=64),
        ),
    ]
